(function(){'use strict';var d;d||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,g="function"==typeof importScripts,ba="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,ca=window.__eaglercraftXLoaderContextPre.loaderWASMURL;d.locateFile=function(a){return"loader.wasm"===a?ca:a};
var k=window.__eaglercraftXLoaderContextPre.rootElement,da=window.__eaglercraftXLoaderContextPre.eaglercraftXOpts,r=window.__eaglercraftXLoaderContextPre.theEPWFileBuffer,ea=window.__eaglercraftXLoaderContextPre.splashURL;delete window.__eaglercraftXLoaderContextPre;var u=[null];
function fa(){for(var a=null,b;b=k.lastChild;)a||=b,k.removeChild(b);b=document.createElement("div");b.classList.add("_eaglercraftX_wrapper_element");b.setAttribute("style","position:relative;width:100%;height:100%;overflow:hidden;");a&&(a.classList.add("_eaglercraftX_early_splash_element"),a.style.position="absolute",a.style.top="0px",a.style.left="0px",a.style.right="0px",a.style.bottom="0px",a.style.zIndex="2",b.appendChild(a));k.appendChild(b);return b}function v(){d=w=x=y=z=null}
var ha=Object.assign({},d),A=[],B="./this.program",C=(a,b)=>{throw b;},D="",E,F,G;
if(ba){var fs=require("fs"),H=require("path");D=g?H.dirname(D)+"/":__dirname+"/";E=(a,b)=>{a=I(a)?new URL(a):H.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};G=a=>{a=E(a,!0);a.buffer||(a=new Uint8Array(a));return a};F=(a,b,e,c=!0)=>{a=I(a)?new URL(a):H.normalize(a);fs.readFile(a,c?void 0:"utf8",(f,p)=>{f?e(f):b(c?p.buffer:p)})};!d.thisProgram&&1<process.argv.length&&(B=process.argv[1].replace(/\\/g,"/"));A=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=d);process.on("uncaughtException",
a=>{if(!("unwind"===a||a instanceof J||a.context instanceof J))throw a;});C=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||g)g?D=self.location.href:"undefined"!=typeof document&&document.currentScript&&(D=document.currentScript.src),D=D.startsWith("blob:")?"":D.substr(0,D.replace(/[?#].*/,"").lastIndexOf("/")+1),E=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},g&&(G=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
F=(a,b,e)=>{var c=new XMLHttpRequest;c.open("GET",a,!0);c.responseType="arraybuffer";c.onload=()=>{200==c.status||0==c.status&&c.response?b(c.response):e()};c.onerror=e;c.send(null)};d.print||console.log.bind(console);var K=d.printErr||console.error.bind(console);Object.assign(d,ha);ha=null;d.arguments&&(A=d.arguments);d.thisProgram&&(B=d.thisProgram);d.quit&&(C=d.quit);var L;d.wasmBinary&&(L=d.wasmBinary);var w,M=!1,x,y,z;
function ia(){var a=w.buffer;d.HEAP8=new Int8Array(a);d.HEAP16=new Int16Array(a);d.HEAPU8=x=new Uint8Array(a);d.HEAPU16=new Uint16Array(a);d.HEAP32=y=new Int32Array(a);d.HEAPU32=z=new Uint32Array(a);d.HEAPF32=new Float32Array(a);d.HEAPF64=new Float64Array(a)}var ja=[],ka=[],la=[],ma=[];function na(){var a=d.preRun.shift();ja.unshift(a)}var O=0,Q=null,R=null,oa=a=>a.startsWith("data:application/octet-stream;base64,"),I=a=>a.startsWith("file://"),S;S="loader.wasm";
if(!oa(S)){var pa=S;S=d.locateFile?d.locateFile(pa,D):D+pa}function qa(a){if(a==S&&L)return new Uint8Array(L);if(G)return G(a);throw"both async and sync fetching of the wasm failed";}
function ra(a){if(!L&&(aa||g)){if("function"==typeof fetch&&!I(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>qa(a));if(F)return new Promise((b,e)=>{F(a,c=>b(new Uint8Array(c)),e)})}return Promise.resolve().then(()=>qa(a))}
function sa(a,b,e){return ra(a).then(c=>WebAssembly.instantiate(c,b)).then(e,c=>{K(`failed to asynchronously prepare wasm: ${c}`);d.onAbort?.(c);c="Aborted("+c+")";K(c);M=!0;throw new WebAssembly.RuntimeError(c+". Build with -sASSERTIONS for more info.");})}
function ta(a,b){var e=S;L||"function"!=typeof WebAssembly.instantiateStreaming||oa(e)||I(e)||ba||"function"!=typeof fetch?sa(e,a,b):fetch(e,{credentials:"same-origin"}).then(c=>WebAssembly.instantiateStreaming(c,a).then(b,function(f){K(`wasm streaming compile failed: ${f}`);K("falling back to ArrayBuffer instantiation");return sa(e,a,b)}))}function J(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var T=a=>{for(;0<a.length;)a.shift()(d)},ua=d.noExitRuntime||!0,U="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,V=a=>{if(a){for(var b=x,e=a+NaN,c=a;b[c]&&!(c>=e);)++c;if(16<c-a&&b.buffer&&U)a=U.decode(b.subarray(a,c));else{for(e="";a<c;){var f=b[a++];if(f&128){var p=b[a++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|p);else{var m=b[a++]&63;f=224==(f&240)?(f&15)<<12|p<<6|m:(f&7)<<18|p<<12|m<<6|b[a++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|
f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}a=e}}else a="";return a},va=a=>{ua||(d.onExit?.(a),M=!0);C(a,new J(a))},wa={k:(a,b,e)=>x.copyWithin(a,b,b+e),c:function(a){console.error("LoaderMain: [ERROR] "+V(a))},b:function(a){console.log("LoaderMain: [INFO] "+V(a))},j:a=>{var b=x.length;a>>>=0;if(67108864<a)return!1;for(var e=1;4>=e;e*=2){var c=b*(1+.2/e);c=Math.min(c,a+100663296);var f=Math;c=Math.max(a,c);a:{f=(f.min.call(f,67108864,c+(65536-c%65536)%65536)-w.buffer.byteLength+65535)/65536;
try{w.grow(f);ia();var p=1;break a}catch(m){}p=void 0}if(p)return!0}return!1},n:function(){return r.byteLength},i:function(){return"undefined"!==typeof WebAssembly.u},f:function(a,b){const e=u.length;u.push(U.decode(new Uint8Array(r,a,b)));return e},e:function(a){const b=u.length;u.push(new Uint8Array(a));return b},d:function(a,b,e){x.set(new Uint8Array(r,b,e),a)},g:function(a,b,e,c){u[a].set(new Uint8Array(r,e,c),b)},l:function(a,b,e,c){u[a].set(new Uint8Array(x.buffer,b,c),e)},a:function(a){r=u=
null;setTimeout(v,20);const b=fa(),e=document.createElement("div");e.setAttribute("style","z-index:100;position:absolute;top:10%;left:10%;right:10%;bottom:10%;background-color:white;border:2px solid #cccccc;overflow-x:hidden;overflow-y:scroll;");e.classList.add("_eaglercraftX_loader_failed_container");a=V(a);console.error("LoaderMain: [FAILED] "+a);const c=document.createElement("h2");c.style.color="#AA0000";c.style.padding="25px";c.style.fontFamily="sans-serif";c.style.marginBlock="0px";c.appendChild(document.createTextNode(a));
e.appendChild(c);a=document.createElement("h4");a.style.color="#AA0000";a.style.padding="25px";a.style.fontFamily="sans-serif";a.style.marginBlock="0px";a.appendChild(document.createTextNode("Try again later"));e.appendChild(a);b.appendChild(e)},h:function(a){var b=a>>2;a=u[y[b]];var e=u[y[b+1]];a=a?URL.createObjectURL(new Blob([a],{type:e||"image/png"})):null;b=(b=u[y[b+2]])?U.decode(b):"<h1>Failed to load error screen</h1>";r=u=null;setTimeout(v,20);e=fa();var c=document.createElement("img");c.setAttribute("style",
"z-index:100;position:absolute;top:10px;left:calc(50% - 151px);");c.src=a;e.appendChild(c);a=document.createElement("div");a.setAttribute("style","z-index:100;position:absolute;top:135px;left:10%;right:10%;bottom:50px;background-color:white;border:2px solid #cccccc;");a.classList.add("_eaglercraftX_jspi_unsupported_container");c=document.createElement("iframe");c.classList.add("_eaglercraftX_jspi_unsupported_frame");c.setAttribute("style","border:none;width:100%;height:100%;");c.srcdoc=b;a.appendChild(c);
e.appendChild(a)},m:function(a){a>>=2;const b=URL.createObjectURL(new Blob([u[y[a]]],{type:"text/javascript;charset=utf-8"})),e=URL.createObjectURL(new Blob([u[y[a+1]]],{type:"application/wasm"})),c=URL.createObjectURL(new Blob([u[y[a+2]]],{type:"application/octet-stream"})),f=URL.createObjectURL(new Blob([u[y[a+3]]],{type:"application/wasm"})),p=URL.createObjectURL(new Blob([u[y[a+4]]],{type:u[y[a+5]]})),m=URL.createObjectURL(new Blob([u[y[a+6]]],{type:u[y[a+7]]})),Y=URL.createObjectURL(new Blob([u[y[a+
8]]],{type:u[y[a+9]]})),N=y[a+10],t=Array(N);for(var h=0,l;h<N;++h)l=a+11+3*h,t[h]={data:u[y[l]],name:u[y[l+1]],path:u[y[l+2]]};r=u=null;setTimeout(v,20);window.__eaglercraftXLoaderContext={getEaglercraftXOpts:function(){return da},getEagRuntimeJSURL:function(){return b},getClassesWASMURL:function(){return e},getClassesDeobfWASMURL:function(){return f},getClassesTEADBGURL:function(){return c},getEPKFiles:function(){return t},getRootElement:function(){return k},getMainArgs:function(){return[]},getImageURL:function(q){switch(q){case 0:return ea;
case 1:return p;case 2:return m;case 3:return Y;default:return null}},runMain:function(q){setTimeout(q,10)}};a=document.createElement("script");a.type="text/javascript";a.src=b;document.head.appendChild(a)}},W=function(){function a(e){W=e.exports;w=W.o;ia();ka.unshift(W.p);O--;d.monitorRunDependencies?.(O);0==O&&(null!==Q&&(clearInterval(Q),Q=null),R&&(e=R,R=null,e()));return W}var b={a:wa};O++;d.monitorRunDependencies?.(O);if(d.instantiateWasm)try{return d.instantiateWasm(b,a)}catch(e){return K(`Module.instantiateWasm callback failed with error: ${e}`),
!1}ta(b,function(e){a(e.instance)});return{}}(),xa=d._main=(a,b)=>(xa=d._main=W.q)(a,b),X=a=>(X=W.s)(a),Z;R=function ya(){Z||za();Z||(R=ya)};
function Aa(a=[]){var b=xa;a.unshift(B);var e=a.length,c=X(4*(e+1)),f=c;a.forEach(m=>{for(var Y=z,N=f>>2,t=0,h=0;h<m.length;++h){var l=m.charCodeAt(h);127>=l?t++:2047>=l?t+=2:55296<=l&&57343>=l?(t+=4,++h):t+=3}var q=t+1;h=t=X(q);l=x;if(0<q){q=h+q-1;for(var P=0;P<m.length;++P){var n=m.charCodeAt(P);if(55296<=n&&57343>=n){var Ca=m.charCodeAt(++P);n=65536+((n&1023)<<10)|Ca&1023}if(127>=n){if(h>=q)break;l[h++]=n}else{if(2047>=n){if(h+1>=q)break;l[h++]=192|n>>6}else{if(65535>=n){if(h+2>=q)break;l[h++]=
224|n>>12}else{if(h+3>=q)break;l[h++]=240|n>>18;l[h++]=128|n>>12&63}l[h++]=128|n>>6&63}l[h++]=128|n&63}}l[h]=0}Y[N]=t;f+=4});z[f>>2]=0;try{var p=b(e,c);va(p)}catch(m){m instanceof J||"unwind"==m||C(1,m)}}
function za(){var a=A;function b(){if(!Z&&(Z=!0,d.calledRun=!0,!M)){T(ka);T(la);if(d.onRuntimeInitialized)d.onRuntimeInitialized();Ba&&Aa(a);if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var e=d.postRun.shift();ma.unshift(e)}T(ma)}}if(!(0<O)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)na();T(ja);0<O||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},1);b()},1)):b())}}
if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();var Ba=!0;d.noInitialRun&&(Ba=!1);za();}).call(this);
