import org.teavm.gradle.api.OptimizationLevel
import org.teavm.gradle.api.WasmDebugInfoLocation
import org.teavm.gradle.api.WasmDebugInfoLevel

plugins {
    id "java"
    id "eclipse"
    id "org.teavm" version "0.11.0-EAGLER-R1"
}

sourceSets {
    main {
        java {
            srcDirs(
                "../src/main/java",
                "../src/game/java",
               	"../src/protocol-game/java",
                "../src/wasm-gc-teavm/java"
            )
            exclude "net/lax1dude/eaglercraft/v1_21/**"
        }
    }
    
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://eaglercraft-teavm-fork.github.io/maven/")
    }
    mavenCentral()
}

dependencies {
    compileOnly "org.teavm:teavm-core:0.11.0-EAGLER-R1" // workaround for a few hacks
}

def folder = "javascript"
def name = "classes.wasm"

teavm.wasmGC {
    compileJava.options.encoding = "UTF-8"
    targetFileName = "../" + name
    optimization = OptimizationLevel.BALANCED
    outOfProcess = false
    fastGlobalAnalysis = false
    processMemory = 512
    mainClass = "net.lax1dude.eaglercraft.internal.wasm_gc_teavm.MainClass"
    outputDir = file(folder)
    properties = [ "java.util.TimeZone.autodetect": "true" ]
    debugInformation = false
	directMallocSupport = true
    minHeapSize = 16
    maxHeapSize = 128
    disassembly = true
}
